### ISSUE TITLE
transform和required的冲突

### ISSUE THREAD

**Issue by 233cy** [yiminghe/async-validator#191]
`
avatar: [{
        required: true,
        type: 'string',
        message: '请上传一个有效头像',
        transform: (value) => {
            return this.utils.isApiUrl(value)
        }
}]
`
以上代码是我的一个校验规则
`
this.$refs['form'].validate((valid) => {
    if (valid) {
        this.view.loading = true
    }
})
`
以下是我的form提交的时候做一次规则校验。

问题：
当我将规则的required改成false，表示不需要强行校验的时候，提交表单依旧会校验。
但当我去掉transform的时候，required的作用就会起作用。

**Comment by 233cy** [comment]
@noyobo

**Comment by ygj6** [comment]
The problem lies in the implementation of your transform function. From the source code you provided, it is guessed that transform is converted to a Boolean value when the value is empty, which causes the validation to take effect. Suggestion: When the input is empty, the transform will increase the judgment, and the value will not be transformed.
```
          avatar: [{ required: false, type: 'string', message: 'some messages', transform: (value) => { if (value !== '') { return this.utils.isApiUrl(value) } } }],

```

**Comment by ygj6** [comment]
Closed，reopen if any problem.
