### ISSUE TITLE
How to avoid printting warnings automatically?

### ISSUE THREAD

**Issue by yangdm2015** [yiminghe/async-validator#92]
When using the validate method, there are a lot of warnings printed on the console, how to avoid that?
`let validator = new schema(descriptor);
      validator.validate(curObj, (errors, errorfields) => {})`

**Comment by reyronald** [comment]
I came here exactly for this, currently I am testing some validation rules using Jest in my React components and the console is full of unwanted warning messages. I looked at the source code and found this bit:

https://github.com/yiminghe/async-validator/blob/e782748f0345b462d84e96a582c0dd38db2de666/src/util.js#L6-L17

So basically they are not supposed to show if it's running in a node environment, however, since most front-end testing tools now days use JSDOM, checking for the definition of `window` and `document` is not really conclusive.

I thought about submitting a pull request adding a check for a `test` NODE_ENV, how do the owners / maintainers feel about this? Although I think the optimal solution would be to add a parameter so the user can decide for himself whether he wants them or not.

---

@yangdm2015 In the mean time, I am doing this to prevent them from appearing:

```js
// Before running my tests
const warn = console.warn
console.warn = () => {}

// Run my tests ...

// After running my tests, restore
console.warn = warn
```

**Comment by yangdm2015** [comment]
Thanks, it works

**Comment by MiroslavPetrik** [comment]
Any change in this? I would like to turn off those warnings in test environment...

**Comment by jacobgarcia** [comment]
Any news on this?

**Comment by HypertextPP** [comment]
For anyone who doesn't necessarily have access to the raw Schema object (such as if you're using ElementUI like me), the following **hack** works just fine:
```javascript
const warn = console.warn
console.warn = (...args: any[]) => {
  if(typeof args[0] === 'string' && args[0].startsWith('async-validator:')) return

  warn(...args)
}
```

Pop that in your entrypoint (`main.js` for me) and Bob's yer uncle.

**Comment by xiGUAwanOU** [comment]
Maybe a stupid question. Why is console warning implemented in the first place?

**Comment by tsurumure** [comment]
Seriously. Please delete this warning.

**Comment by sli** [comment]
Mutating built-in globals is absolutely not a real fix for this. It needs to be an opt-in feature.

**Comment by yiminghe** [comment]
option added: https://github.com/yiminghe/async-validator/commit/e5dba0e927b580d079f88f5ce3b77396bf703e31

**Comment by lPaths** [comment]
> option added: [e5dba0e](https://github.com/yiminghe/async-validator/commit/e5dba0e927b580d079f88f5ce3b77396bf703e31)

I think the warning should be disabled by default...

**Comment by JounQin** [comment]
@yiminghe Still no way to disable it globally in antd?

**Comment by yiminghe** [comment]
> @yiminghe Still no way to disable it globally in antd?

https://github.com/yiminghe/async-validator/commit/2a1ba5a7067e1447a4d18e1b0c843321bd55720e
